name: Code Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: run coverage tests and upload
      run: |
        cargo tarpaulin--skip-clean --out Xml &&
        bash <(curl -s https://codecov.io/bash)
