name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make folder
      run: mkdir -p tests/test_dir
    - name: Run tests
      run: cargo test -v -- --test-threads=1
